### ISSUE TITLE
A few minor issues

### ISSUE THREAD

**Issue by yarusome** [Vallek/animatable-css#1] opened 2023-06-26 01:52 UTC
1. `index.js` seems not included in the GitHub Page.
2. For the animation type of `z-index`, the first paragraph in [Appendix A](https://drafts.csswg.org/web-animations-1/#animation-types) of Web Animations implies that it should be "by computed value", thus MDN is incorrect here. ~(Although for integer-valued properties, "by computed value" and "discrete" exhibit the same behavior.)~

Kudos to your job so far :+1: You may also visit the somewhat related my [diff-webref-mdn](https://github.com/yarusome/diff-webref-mdn) repo.

**Comment by Vallek** [comment] 2023-06-26 05:52
@yarusome Thanks for feedback! The last commit broke the build btw so properties weren't loaded, it's fixed now. upd (aaaand happened again)

1. Yes this is by design. index.html is build from index.js on node.js by github actions and then put in gh-pages.
2. Oh that's interesting. So should everything from [Other cases](https://vallek.github.io/animatable-css/#other) have "by computed value"? Cause it's not in api right?
3. I was looking for mdn api but didn't found it. So there is one) Well seems like they deprecating it https://github.com/mdn/data/#welcome-to-mdn-data in favor of [w3c/webref](https://github.com/w3c/webref)

**Comment by yarusome** [comment] 2023-06-26 12:01
1. OK, when I visited the page, the two sections were blank, but not anymore now :)
2. Yes.
3. The deprecation seems stalled. I do see its value since most developers cannot easily tell which level of each spec has actually been widely implemented.

**Comment by Vallek** [comment] 2023-06-26 12:29
@yarusome 
2. Ok, well since animation not applied to voice (i'm guessing) I think I can remove that spec entirely and put everything else with "by computed value".

PS I don't think you should close issues yourself in others repos) There still might be something to discuss. More importantly people should see if it's not fixed yet.

**Comment by yarusome** [comment] 2023-06-26 13:46
The main issue was Point 1, but fair enough, I'm reopening the issue.

---

Actually, the presence of both Level 3 and Level 4 of CSS Backgrounds and Borders Module on the page underscores [Point 3](https://github.com/Vallek/animatable-css/issues/1#issuecomment-1607323323).

Another minor issue I found with the current layout is that some specs have so many properties that a single column becomes really lengthy. Instead of using `break-inside: avoid`, and for better use of the space while keeping the multi-column layout, it could be done that:

1. Remove the `lists` class;

2. Use something like below:

   ```css
   @media screen and (min-width: 800px) {
     section > ul {
       display: flex;
       flex-wrap: wrap;
     }
     section > ul > li {
       margin-right: 3%;
       width: 30%;
     }
   }
   ```

   or even more gradual transition:

   ```css
   @media screen and (min-width: 500px) {
     section > ul {
       display: flex;
       flex-wrap: wrap;
     }
     section > ul > li {
       margin-right: 5%;
       width: 45%;
     }
   }
   @media screen and (min-width: 800px) {
     section > ul > li {
       margin-right: 3%;
       width: 30%;
     }
   }
   ```

**Comment by Vallek** [comment] 2023-06-26 18:56
Ok, so I checked some of those other values again and they are not all animatable. [wrap-flow](https://www.w3.org/TR/css3-exclusions/#propdef-wrap-flow) explicitly says `No` on specs page, but in api there is no `animatable` property at all.

I think i'll leave it at that for now. Because the goal is to make it 100% auto (outside of values checks in JS). I added a bit for disclaimer that api and specs may differ.

>most developers cannot easily tell which level of each spec has actually been widely implemented

Yeah I'm definitely one of them! But i'm not sure I understood your point. Do you suggest I put info here from there? 

---

Oh there's a lot to be improved in CSS for sure) I just put together something working and minimal quick. I also made that 3 column layout like on MDN deleted page. But flexbox approach also have problems. Long lists look better for sure, but now short ones create empty spaces and imo less readable. I'll think about it. 

This page is for quick search and not reading all of that in one go anyways.

But I do appreciate your input a lot! If you have any more ideas please share. If it's ok I will close this issue before it drift too far away)

**Comment by yarusome** [comment] 2023-06-27 01:11
The "Animatable" entries are remnants of the overall transition in CSS specs from "Animatable" to "Animation types" (I couldn't find a specific issue in CSSWG to reflect this, though), and the specs you mentioned haven't been updated for a long time.

---

I meant that devs should be warned of conflicts of different levels of specs if these levels coexist on the same page :)

**Comment by Vallek** [comment] 2023-06-27 10:51
Yeah I never even heard of wrap-flow) But then again i don't want to pick it manually unless there's some indication in api.

---

Sure. I added another bit to disclaimer)

Ok I'm closing this for now then. Thanks!

**Closed as completed by Vallek** 2023-06-27 10:51 UTC
